version: 2.1

orbs:
  node: circleci/node@3.0.0
  docker: circleci/docker@1.2.1

jobs:
  build-and-test-client:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: './client'
      - run:
          command: |
            cd ./client
            npm test
          name: "npm test"

  build-and-test-server:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: './server'
      - run:
          command: |
            cd ./server
            npm test
          name: "npm test"

workflows:
    build-test-publish:
      jobs:
        - build-and-test-client
        - build-and-test-server
        - docker/publish:
            path: ./client
            docker-context: ./client
            image: $DOCKER_LOGIN/client
            tag: latest
            requires:
              - build-and-test-client

        - docker/publish:
            path: ./server
            docker-context: ./server
            image: $DOCKER_LOGIN/api
            tag: latest
            requires:
              - build-and-test-server
